services:
  - type: web
    name: inventory-system
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn inventory_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inventory-db
          property: connectionString

databases:
  - name: inventory-db

